### PR TITLE
Update for EnderIO 5.2.60 (Fixes #18)

### LINKED ISSUE #18: ET 1.2.0 not yet Compatible with EIO 5.2.60
Heya ;)
Hope I reach you here.
See my Post on Curseforge.
EnderIO Updated quite a lot and their current build is much more stable and more performant then the older ones.
I always update and handcraft compatibility for my own Version of PO3 and the current version of ET 1.2.0 just supports up to EIO 5.1.53.
I think not just PO3 OG will benefit from an update to EIO 5.2.60.
Most Recipes are heavily dependent on ET (especially in Kappa Mode).
Almost every EnderIO recipe for Kappa mode is being changed through ET and therefore will be broken (Items aren’t craftable/producible anymore and the basic recipes brake the game difficulty and EMC values significantly).
Hope we can count on an update to EIO 5.2.60 Soon.
Bless your work with the CraftTweaker integration of EIO so far 👍

### PR DESCRIPTION
**Pull request by ElektroKill**
I went ahead and updated this mod to work with EnderIO version 5.2.60 and above.

I hope a build of this could be released to curseforge.

Thanks!

### CODE REVIEW

**Comment by ElektroKill** [comment]
@Shadows-of-Fire Any updates on this?

EDIT: Sorry for the mention, just saw what you said in the issue.

**Comment by ElektroKill** [comment]
Any updates on this?

**Comment by Shadows-of-Fire** [comment]
Why were the mappings moved from stable to a 2017 snapshot...?

**Comment by ElektroKill** [comment]
@Shadows-of-Fire the stable once are no longer hosted on forge servers. When I run the setupDecompWorkspace task it threw a bunch of errors that it was unable to access the files.

**Pull request merged**
